#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 4

#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION

#define PLOOPY_DPI_OPTIONS {1200}
#define PLOOPY_DPI_DEFAULT 0

#define PLOOPY_DRAGSCROLL_MOMENTARY
#define PLOOPY_DRAGSCROLL_INVERT
#define PLOOPY_DRAGSCROLL_DIVISOR_H 64.0
#define PLOOPY_DRAGSCROLL_DIVISOR_V 64.0
